### ISSUE TITLE
Wallpaper not loaded

### ISSUE THREAD

**Issue by shinkuan** [Darkkal44/Cozytile#12]
Hello, I really like Cozytile's themes, thank you for making it.

I encounter some problems when I try to install it. I was using VirtualBox, running a fresh install Arch Linux. I installed it by using the install.sh file.

First problem was that I was using a VM on a Desktop, so the battery status bar shows an error: `Error: Fail to read status for status_file`. Which is not a big problem, I commented out the battery part in Qtile's config.

And the other problems are that wallpaper is not loaded, showing black background, and the rounded corner is not showing.
![VirtualBox_Arch_18_07_2023_00_07_24](https://github.com/Darkkal44/Cozytile/assets/35415788/5b94856c-a62a-47e4-891d-845254ebcfd4)

How can I resolve this? Thanks.

**Comment by Darkkal44** [comment]
First of all im extremely sorry for the late reply, i have been really busy and unable to give my attention to this project, I will be reworking on this project in April. And the issue you got with the battery module is simply because you are using a pc and it doesn't have a battery (will be fixed in the rework) and finally the wallpaper issue is something that i have to figure out, and im sure i will fix it in the rework as well. Thankyou so much for testing it out.

**Comment by Darkkal44** [comment]
Many issues within picom can be simply fixed by turning on "3d acceleration" in the vm settings and the installation script has been fixed. Sorry for being way too late with the fix!
