### ISSUE TITLE
Install bugged from base arch using install script or manual installation, 

### ISSUE THREAD

**Issue by phillip-simons** [Darkkal44/Cozytile#13]
When signing in from sddm, only the bar loads but an an incorrect resolution. Most functional aspects technically work, but sddm splash screen is never dismissed. When switching workspaces, all windows stay on screen, but can no longer be interacted with until I go back to the original

When trying `qtile check` I get this error:
```
Checking Qtile config at: /home/user/.config/qtile/config.py
error: config.extension_defaults variable differs from runtime type builtins.list[Any]
Stub: in file /tmp/tmpih5z8vhu/config.pyi:20
builtins.dict[builtins.str, Any]
Runtime:
[{'font': 'sans', 'fontsize': 12, 'padding': 3}]

Found 1 error (checked 1 module)
```
I am not familiar enough with qtile to parse this and wasn't able to find a solution online

**Comment by phillip-simons** [comment]
After messing around for a couple hours I was able to fix some things:
First I removed the square brackets on the line referenced in the error above to end up with this -
`extension_defaults = widget_defaults.copy()`
This brings it in line with the example configuration in the qtile documentation and fixes the error on `qtile check`

And the auto start script isn't launching on startup(which I still haven't been able to fix, I am just running it manually once I login), which seems to fix most things, though it is significantly more buggy than is usable. I also had the change the blur level in picom.conf which was at 49, because the maximum value was 20.

While throwing myself into the fire here was a good crash course in qtile, this is probably as far as I'll get with this rice, which is unfortunate because I think it is one of the best looking out there

**Comment by Darkkal44** [comment]
First of all, I'm so sorry about all the errors. Iam indeed new ro ricing and python in general but I will try my level best to get everything to work. Lately I have been busy and havnt been able to update this rice nor fix the issues, And currently this rice is not really usable, but People can definitely take inspiration or check out the dots to see how things are done. It is currently having some issues and I will fix them as soon as I get some free time. And thanks a lot of these informations, helps me a ton. 
I will update the rice with all the currently open issues fixed soon. Thanks a ton for letting me know that you love the look of this rice. Much appreciated.

**Comment by Darkkal44** [comment]
As far as I know, Most of the issues that you have mentioned over here is due to picom having a wrong configuration, I used to have the same error, like windows stay the same (like a wallpaper) when switching workspaces, and sddm screen staying as it is, this issue is also cause by picom. Im extremely sorry for this and will fix it as soon as possible. Its nothing related to Qtile configuration.

**Comment by AiZr-01** [comment]
I was able to solve several of the installation problems with the command that @phillip-simons  provided, it took several attempts but what in the end worked for me is that before following the manual installation steps it was necessary to install the following packages: "picom"  because archlinux did not have this and "python-pywal" for "autostart_once.sh" to work correctly. At the moment it only works with the EverForest theme, but it was the only one I tried to fix because it's my favorite, anyway it's one of my favorite qtile customizations hopefully the installer can be fixed soon

**Comment by Darkkal44** [comment]
Thanks a lot to @phillip-simons for that line, I think I will change it in the repo and also fix the startup issues, I've been a bit busy lately and havnt been able to work on this rice.. but I will try my level best to get back to it asap. And I will let you guys know when its all ready and I will try my best to make it a buggy-less experience.

**Comment by Darkkal44** [comment]
The installation script has been revamped and it works perfectly fine now. Make sure to turn on "3d acceleration" on if you're working with virtual machines!
