### ISSUE TITLE
Bar rounded corners

### ISSUE THREAD

**Issue by ShambuKumar** [Darkkal44/Cozytile#8]
Hi! I used your install script on a minimal arch install and it worked fine(except for the wallpaper appearing to be missing, and this issue of course). (Very well made rice btw. Great install experience!) I noticed that the bar doesn't have rounded corners. I am sorry if this is intentional, but if not and you have any ideas what could be causing the problem I would love hear it! I manually reinstalled the dependencies and reloaded qtile, but it still seems to be a problem. Thank you in advance! Edit: I just needed to wait a fee seconds after I rebooted my machine, don't know id this is an issue on only my side, if not you should maybe include that in the installation.

**Comment by Darkkal44** [comment]
Hi! First of all tysmm for the kind words.. I appreciate that a ton! I can definitely understand the issue, its not actually an issue; the first startup usually takes a while. This is because, the wallpaper is being set by a utility called pywal, and some of the wallpaper in this rice is pretty much monochromatic and thus pywal takes a bit of time to load up. And this is only the case when you set a theme for the first time, next time onwards, its gonna be launched in 7-15 seconds.. depends on your specs Ig.
And picom gets executed only after the wallpaper is set by pywal.. thus the rounded corner wasn't working for you.. 
Now that you have figured out the issue on your own, i think it should be working rather fine for ya! And I think I need to put a msg in the installation script saying "on the first launch it takes time" lol.
